<a href="https://colab.research.google.com/github/olvad/ML_course_openEdu/blob/main/Homeworks/HW1_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# скачиваем файл
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1cq9JDz8-zwzoGL6udiT_ogHHRWdnsd1q' -O math_students.csv

--2024-07-02 14:16:25--  https://docs.google.com/uc?export=download&id=1cq9JDz8-zwzoGL6udiT_ogHHRWdnsd1q
Resolving docs.google.com (docs.google.com)... 108.177.97.138, 108.177.97.102, 108.177.97.139, ...
Connecting to docs.google.com (docs.google.com)|108.177.97.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1cq9JDz8-zwzoGL6udiT_ogHHRWdnsd1q&export=download [following]
--2024-07-02 14:16:26--  https://drive.usercontent.google.com/download?id=1cq9JDz8-zwzoGL6udiT_ogHHRWdnsd1q&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 74.125.23.132, 2404:6800:4008:c02::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|74.125.23.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42379 (41K) [application/octet-stream]
Saving to: ‘math_students.csv’

math_students.csv   100%[===================>]  41.39K  --.-KB/s    in 0.001s

2024-07-02 14:16:26 (80.5 MB/s) - ‘math_students.csv’ saved [42379/42379]

In [ ]:
import pandas as pd
data = pd.read_csv('math_students.csv', delimiter=',')

In [ ]:
data

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

1. Какая причина выбора школы была самой частой? В качестве ответа приведите соответствующее значение признака.

In [ ]:
most_common_reason = data['reason'].value_counts()
most_common_reason

reason
course        145
home          109
reputation    105
other          36
Name: count, dtype: int64

2. Найдите количество студентов, у родителей которых нет никакого образования.

In [ ]:


data[
    (data['Medu'] ==  0) & (data['Fedu'] == 0)
].shape[0]

0

3. Найдите минимальный возраст учащегося школы Mousinho da Silveira.

In [ ]:
data[data['school'] == 'MS'].age.min()

17

4. Найдите количество студентов, имеющих нечетное число пропусков.

In [ ]:
data[data['absences'] % 2 == 1].shape

(41, 33)

5. Найдите разность между средними итоговыми оценками студентов, состоящих и не состоящих в романтических отношениях. В качестве ответа приведите число, округленное до двух значащих цифр после запятой.

In [ ]:
round(data.groupby('romantic')['G3'].mean()['yes'] - data.groupby('romantic')['G3'].mean()['no'],2)

-1.26

6. Сколько занятий пропустило большинство студентов с самым частым значением наличия внеклассных активностей?

*Примечание. В данном контексте под "большинством" подразумеваются студенты, имеющее самое частое значение пропусков. То есть в данном задании необходимо:*


* *Определить самое частое значение наличия внеклассных активностей (да или нет).*
* *Для группы студентов, соответствующей этому значению, рассмотреть значения признака «число пропусков».*
* *Для каждого значения числа пропусков посчитать, сколько студентов ему соответствует.*
* *Выбрать значение числа пропусков с наибольшим числом студентов.*

In [ ]:


most_common_activity = data['activities'].value_counts().index[0]
filtered_data = data[data['activities'] == most_common_activity]
filtered_data
filtered_data['absences'].value_counts()

absences
0     51
2     37
4     29
6     17
8     16
10     9
14     7
16     4
3      4
15     3
7      3
12     3
11     2
9      2
1      2
20     2
18     2
56     1
13     1
22     1
30     1
54     1
25     1
17     1
5      1
Name: count, dtype: int64